// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetFlow.Persistence;

#nullable disable

namespace PetFlow.Persistence.Migrations
{
    [DbContext(typeof(PetFlowFlowDbContext))]
    partial class PetFlowFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfEvent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("TEXT");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reminder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(4953),
                            CreatedBy = "3.01.2026 22:44:57",
                            DateOfEvent = new DateTime(2026, 1, 10, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(5747),
                            Description = "Annual checkup for Max",
                            Reminder = true,
                            StatusId = 1,
                            Title = "Vet Appointment"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(4953),
                            CreatedBy = "3.01.2026 22:44:57",
                            DateOfEvent = new DateTime(2026, 1, 6, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(6078),
                            Description = "Bath and nail trimming for Whiskers",
                            Reminder = false,
                            StatusId = 1,
                            Title = "Grooming Session"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(4953),
                            CreatedBy = "3.01.2026 22:44:57",
                            DateOfEvent = new DateTime(2026, 1, 17, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(6096),
                            Description = "Rabies vaccination for Buddy",
                            Reminder = true,
                            StatusId = 1,
                            Title = "Vaccination"
                        });
                });

            modelBuilder.Entity("Domain.Entities.MedicalNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("TEXT");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("MedicalNotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(8684),
                            CreatedBy = "3.01.2026 22:44:57",
                            Description = "Started antibiotic treatment for Max's ear infection",
                            PetId = 1,
                            StatusId = 1,
                            Title = "Ear Infection Treatment"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(8684),
                            CreatedBy = "3.01.2026 22:44:57",
                            Description = "Professional dental cleaning performed for Whiskers",
                            PetId = 2,
                            StatusId = 1,
                            Title = "Dental Cleaning"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(8684),
                            CreatedBy = "3.01.2026 22:44:57",
                            Description = "Buddy needs to reduce weight by 2kg - started new diet plan",
                            PetId = 3,
                            StatusId = 1,
                            Title = "Weight Management"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("TEXT");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Max seems to have good energy today",
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(7245),
                            CreatedBy = "3.01.2026 22:44:57",
                            PetId = 1,
                            StatusId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Whiskers was very playful during the afternoon",
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(7245),
                            CreatedBy = "3.01.2026 22:44:57",
                            PetId = 2,
                            StatusId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Content = "Buddy ate all his meals today",
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 25, DateTimeKind.Utc).AddTicks(7245),
                            CreatedBy = "3.01.2026 22:44:57",
                            PetId = 3,
                            StatusId = 1,
                            Type = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("TEXT");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Golden Retriever",
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 20, DateTimeKind.Utc).AddTicks(4271),
                            CreatedBy = "3.01.2026 22:44:57",
                            DateOfBirth = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Max",
                            PhotoUrl = "https://example.com/max.jpg",
                            Species = "Dog",
                            StatusId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Breed = "British Shorthair",
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 20, DateTimeKind.Utc).AddTicks(4271),
                            CreatedBy = "3.01.2026 22:44:57",
                            DateOfBirth = new DateTime(2019, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Whiskers",
                            PhotoUrl = "https://example.com/whiskers.jpg",
                            Species = "Cat",
                            StatusId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Breed = "Labrador Retriever",
                            Created = new DateTime(2026, 1, 3, 22, 44, 57, 20, DateTimeKind.Utc).AddTicks(4271),
                            CreatedBy = "3.01.2026 22:44:57",
                            DateOfBirth = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Buddy",
                            Species = "Dog",
                            StatusId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.PetEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("TEXT");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PetId");

                    b.ToTable("PetEvents");
                });

            modelBuilder.Entity("Domain.Entities.MedicalNote", b =>
                {
                    b.HasOne("Domain.Entities.Pet", "Pet")
                        .WithMany("MedicalNotes")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Domain.Entities.Note", b =>
                {
                    b.HasOne("Domain.Entities.Pet", "Pet")
                        .WithMany("Notes")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Domain.Entities.PetEvent", b =>
                {
                    b.HasOne("Domain.Entities.Event", "Event")
                        .WithMany("PetEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Navigation("PetEvents");
                });

            modelBuilder.Entity("Domain.Entities.Pet", b =>
                {
                    b.Navigation("MedicalNotes");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
